### ISSUE TITLE
hitting reply on a post redirects me to internal ip, not reverse proxy

### ISSUE THREAD

**Issue by FraMecca** [gnstaxo/imageboard#10]
Sorry, I can't fix the issue because I don't understand much of the code in the views templates.

![image](https://user-images.githubusercontent.com/21691223/106128654-76e99280-6157-11eb-9e46-93cc6dfe1a09.png)

this is the form were I get the bad redirect.

**Comment by gnstaxo** [comment]
Does the last commit solve this issue? Redirects were not affected by url_prefix

**Comment by FraMecca** [comment]
no, I am using the master so the last commit doesn't solve the issue

**Comment by gnstaxo** [comment]
This commit? 89bf7ebc909b2cc4468a2c4a249aee28a837623c

**Comment by FraMecca** [comment]
It now works. Thank you very much!
