### ISSUE TITLE
wrong ordering of threads

### ISSUE THREAD

**Issue by FraMecca** [gnstaxo/imageboard#12]
I noticed this morning that threads are ordered incorrectly, as you can see from the picture. Posts from 01/02 are displayed before posts from previous in january.
I think you should sort by unix epoch time rather than dates.

![Screenshot_2021-02-01](https://user-images.githubusercontent.com/21691223/106444140-449ca580-6475-11eb-9397-e3c35fbbb68e.png)

**Comment by gnstaxo** [comment]
It maybe was the date format for replies, but threads should be fine, I'd appreciate it if you told me whether c64d4443a0be978bca28e45d20ac347d1cd69f23 solves the issue :)

**Comment by FraMecca** [comment]
Yes, it now works correctly. Thank you very much
