### ISSUE TITLE
css

### ISSUE THREAD

**Issue by ghost** [gnstaxo/imageboard#14]
When someone holds down a key  ( like "aaaaaaaa" for a real long time writing a post, and then sends the post - it breaks the css on the board, and it breaks the css on the main page list of recent topics. The "aaaa" text goes way too far to the right, off the screen and breaks the board css. 

One way to somewhat fix this is to add  
word-wrap: break-word;
word-break: break-all;

For example.......................................................
to fix the board, 

.Thread-text {
        word-wrap: break-word;
        word-break: break-all;
	margin-top: 5px;
}

to fix the home page

.Card-text {
text-align: left;
  margin-left: 5px;
   word-wrap: break-word;
 word-break: break-all;
}

Thank you so much for your image board code, It is awesome!!!!!!!!

**Comment by gnstaxo** [comment]
Thank you! :)
