### ISSUE TITLE
Allow user to specify baseurl

### ISSUE THREAD

**Issue by FraMecca** [gnstaxo/imageboard#5]
Hi,
for using this software behind reverse proxy it would be useful to specify a baseurl so that every link in the template is prefixed with the baseurl:
http://example.com/chan   ---> root of the imageboard

**Comment by gnstaxo** [comment]
To be honest, I was not aware of the existence of reverse proxies, thank you for letting me know

**Comment by FraMecca** [comment]
It wont be that much complex than putting f'{baseurl}/' in front of each decorator and in front of templates hrefs. I don't have the time to open a PR on this right now, sorry.

**Comment by FraMecca** [comment]
thank you very much for implementing this
