### ISSUE TITLE
About reverse proxies

### ISSUE THREAD

**Issue by FraMecca** [gnstaxo/imageboard#8]
https://github.com/gnstaxo/imageboard/commit/bc1c303a795848974b5c9d2d37ea7794521a78de#commitcomment-46051105

why do they not work? I have been using it in my machine for more than a week now

**Comment by gnstaxo** [comment]
I don't know, but waitress had an option for this (url_prefix), which prefixes all the routes automatically without hardcoding the basename. Could you clone the latest version and tell me if it works in your setup?

**Comment by FraMecca** [comment]
It works very well. Didn't work last time I tried but it was a problem with some modifications I made. Very appreciated, thanks
